version: '3'
services:
  api:
    container_name: FastAPI
    build: ./backend/app
    ports:
      - "80:80"
    environment:
        - GRAPH_DB_HOST=neo4j
        - GRAPH_DB_PORT=7687
        - GRAPH_DB_USER=neo4j
        - GRAPH_DB_PASSWORD=neo4jj
  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
        - 7474:7474
        - 7687:7687
    volumes: 
        - neo4j-data:/data
        - neo4j-logs:/logs
        - neo4j-conf:/conf
    environment:
        # neo4j password setting (NEO4J_AUTH=neo4j/<password>)
        - NEO4J_AUTH=neo4j/neo4jj
  react:
    container_name: react-web-app
    image: node:17-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000

# default user and pass "neo4j"

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-conf: